// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// ✅ WEB
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD351sldlHUX2Fa5rTfTEUcTx0XWxXLLNE',
    appId: '1:298280370718:web:6064a8cdd34cac803ae40f',
    messagingSenderId: '298280370718',
    projectId: 'crisis-management-5626d',
    authDomain: 'crisis-management-5626d.firebaseapp.com',
    storageBucket: 'crisis-management-5626d.appspot.com',
    measurementId: 'G-ET3WZL84TW',
  );

  /// ✅ ANDROID
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcmT-U5RabqDwhM1lUqR73DeAonzh69Ek',
    appId: '1:298280370718:android:4c1bc58728775b433ae40f',
    messagingSenderId: '298280370718',
    projectId: 'crisis-management-5626d',
    storageBucket: 'crisis-management-5626d.appspot.com',
  );

  /// ✅ iOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqC0KvYX8h6EwfvIcjDHL8UhA75V2XTCc',
    appId: '1:298280370718:ios:4cffdb6317e482843ae40f',
    messagingSenderId: '298280370718',
    projectId: 'crisis-management-5626d',
    storageBucket: 'crisis-management-5626d.appspot.com',
    iosBundleId: 'com.example.crisisManagement',
  );

  /// ✅ macOS
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqC0KvYX8h6EwfvIcjDHL8UhA75V2XTCc',
    appId: '1:298280370718:ios:4cffdb6317e482843ae40f',
    messagingSenderId: '298280370718',
    projectId: 'crisis-management-5626d',
    storageBucket: 'crisis-management-5626d.appspot.com',
    iosBundleId: 'com.example.crisisManagement',
  );

  /// ✅ Windows
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD351sldlHUX2Fa5rTfTEUcTx0XWxXLLNE',
    appId: '1:298280370718:web:e38a2c0deb25da343ae40f',
    messagingSenderId: '298280370718',
    projectId: 'crisis-management-5626d',
    authDomain: 'crisis-management-5626d.firebaseapp.com',
    storageBucket: 'crisis-management-5626d.appspot.com',
    measurementId: 'G-GX6B5LQTW8',
  );
}
